export const types = {
  PART_ONE_FETCH: 'PART_ONE_FETCH',
  PART_TWO_FETCH: 'PART_TWO_FETCH',
  PART_ONE_LOADING: 'PART_ONE_LOADING',
  PART_TWO_LOADING: 'PART_TWO_LOADING',
  PART_ONE_UPDATE_INPUT: 'PART_ONE_UPDATE_INPUT',
  PART_TWO_UPDATE_INPUT: 'PART_TWO_UPDATE_INPUT',
  PART_ONE_ERR: 'PART_ONE_ERR',
  PART_TWO_ERR: 'PART_TWO_ERR'
};
